interface Response {
  Promise<DOMString> text();
};
interface ReadableStream {};
interface ReadableStreamDefaultReader {
  constructor(ReadableStream stream);
  Promise<undefined> cancel(DOMString reason);
  undefined releaseLock();
};
interface Window {
  Promise<Response> fetch(DOMString url, RequestInit options);
};
dictionary RequestInit {
  AbortSignal signal;
};
interface AbortSignal {
  readonly attribute boolean aborted;
};
interface AbortController {
  constructor();
  readonly attribute AbortSignal signal;
  undefined abort();
};
interface Values {
  Promise<long> readInteger();
  Promise<unsigned long> readUnsigned();
  Promise<boolean> readBoolean();
  Promise<double> readDouble();
};
