typedef DOMString ResponseText;
interface GPU {
  Promise<GPUAdapter?> requestAdapter();
};
interface GPUAdapter {
  Promise<GPUDevice> requestDevice();
};
interface GPUDevice {
  readonly attribute GPUQueue queue;
  GPUCommandEncoder createCommandEncoder();
  GPUSampler createSampler(GPUSamplerDescriptor descriptor);
  GPUBuffer createBuffer(GPUBufferDescriptor descriptor);
  undefined destroy();
};
interface GPUCommandEncoder {
  GPURenderPassEncoder beginRenderPass(GPURenderPassDescriptor descriptor);
  GPUCommandBuffer finish();
};
interface GPURenderPassEncoder { undefined end(); };
interface GPUCommandBuffer {};
interface GPUQueue {
  undefined submit(sequence<GPUCommandBuffer> commandBuffers);
  Promise<undefined> onSubmittedWorkDone();
};
interface SequenceProbe {
  undefined unsignedValues(sequence<unsigned long> values);
};
interface GPUTextureView {};
enum GPULoadOp { "load", "clear" };
enum GPUStoreOp { "store", "discard" };
dictionary GPUColorDict {
  required double r;
  required double g;
  required double b;
  required double a;
};
typedef (sequence<double> or GPUColorDict) GPUColor;
dictionary GPURenderPassColorAttachment {
  required GPUTextureView view;
  GPUColor clearValue;
  required GPULoadOp loadOp;
  required GPUStoreOp storeOp;
};
dictionary GPURenderPassDescriptor {
  required sequence<GPURenderPassColorAttachment?> colorAttachments;
};
enum GPUAddressMode { "clamp-to-edge", "repeat", "mirror-repeat" };
enum GPUFilterMode { "nearest", "linear" };
dictionary GPUSamplerDescriptor {
  DOMString label = "";
  GPUAddressMode addressModeU = "clamp-to-edge";
  GPUFilterMode minFilter = "nearest";
};
interface GPUSampler { attribute DOMString label; };
dictionary EnumInputs {
  required AddressModeAlias mode;
  GPUAddressMode? optionalMode;
  sequence<GPUFilterMode> filters;
};
typedef GPUAddressMode AddressModeAlias;
typedef [EnforceRange] unsigned long long GPUSize64;
typedef unsigned long GPUBufferUsageFlags;
dictionary GPUBufferDescriptor {
  required GPUSize64 size;
  required GPUBufferUsageFlags usage;
  boolean mappedAtCreation = false;
};
interface GPUBuffer {
  ArrayBuffer getMappedRange();
  undefined unmap();
  undefined destroy();
};
typedef (sequence<sequence<ByteString>> or record<ByteString, ByteString>) HeadersInit;
dictionary PostOptions {
  required DOMString method;
  required HeadersInit headers;
  (Blob or URLSearchParams or USVString)? body;
};
interface Blob {};
interface URLSearchParams {};
interface PostHost {
  Promise<Response> fetch(DOMString url, PostOptions options);
};
interface Response {
  readonly attribute unsigned short status;
  readonly attribute boolean ok;
  readonly attribute Headers headers;
  readonly attribute ReadableStream? body;
  Promise<ResponseText> text();
};
interface Headers {
  ByteString? get(ByteString name);
};
interface ReadableStream {};
interface ReadableStreamDefaultReader {
  constructor(ReadableStream stream);
  Promise<undefined> cancel(DOMString reason);
  Promise<ReadableStreamReadResult> read();
  undefined releaseLock();
};
dictionary ReadableStreamReadResult {
  any value;
  boolean done;
};
interface Window {
  Promise<Response> fetch(DOMString url, RequestInit options);
};
dictionary RequestInit {
  AbortSignal signal;
};
interface AbortSignal {
  readonly attribute boolean aborted;
};
interface AbortController {
  constructor();
  readonly attribute AbortSignal signal;
  undefined abort();
};
interface Values {
  Promise<Response?> readOptionalResponse();
  Promise<RequiredResult> readRequired();
  Promise<long> readInteger();
  Promise<unsigned long> readUnsigned();
  Promise<boolean> readBoolean();
  Promise<double> readDouble();
};
dictionary RequiredResult {
  required boolean done;
};
